// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using eAgenda.WebApp.Compartilhado.Infra.Orm;

#nullable disable

namespace eAgenda.WebApp.Compartilhado.Infra.Orm.Migrations
{
    [DbContext(typeof(EAgendaDbContext))]
    [Migration("20260715035613_Add_CK_TBCompromisso_HorarioValido")]
    partial class Add_CK_TBCompromisso_HorarioValido
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CategoriaDespesa", b =>
                {
                    b.Property<Guid>("CategoriasId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("DespesasId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("CategoriasId", "DespesasId");

                    b.HasIndex("DespesasId");

                    b.ToTable("CategoriaDespesa");
                });

            modelBuilder.Entity("eAgenda.WebApp.ModuloCategoria.Dominio.Categoria", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id")
                        .HasName("PK_TBCategoria");

                    b.HasIndex("Titulo")
                        .IsUnique()
                        .HasDatabaseName("UQ_TBCategoria_Titulo");

                    b.ToTable("TBCategoria", (string)null);
                });

            modelBuilder.Entity("eAgenda.WebApp.ModuloCompromisso.Dominio.Compromisso", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Assunto")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid?>("ContatoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateOnly>("Data")
                        .HasColumnType("date");

                    b.Property<TimeOnly>("HoraInicio")
                        .HasColumnType("time");

                    b.Property<TimeOnly>("HoraTermino")
                        .HasColumnType("time");

                    b.Property<string>("LocalOuLink")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("Tipo")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK_TBCompromisso");

                    b.HasIndex("ContatoId");

                    b.ToTable("TBCompromisso", null, t =>
                        {
                            t.HasCheckConstraint("CK_TBCompromisso_HorarioValido", "[HoraTermino] > [HoraInicio]");
                        });
                });

            modelBuilder.Entity("eAgenda.WebApp.ModuloContato.Dominio.Contato", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Cargo")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Empresa")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Telefone")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.HasKey("Id")
                        .HasName("PK_TBContato");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("UQ_TBContato_Email");

                    b.HasIndex("Telefone")
                        .IsUnique()
                        .HasDatabaseName("UQ_TBContato_Telefone");

                    b.ToTable("TBContato", (string)null);
                });

            modelBuilder.Entity("eAgenda.WebApp.ModuloDespesa.Dominio.Despesa", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Data")
                        .HasColumnType("datetime2");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("FormaPagamento")
                        .HasColumnType("int");

                    b.Property<decimal>("Valor")
                        .HasColumnType("decimal(18, 2)");

                    b.HasKey("Id")
                        .HasName("PK_TBDespesa");

                    b.ToTable("TBDespesa", (string)null);
                });

            modelBuilder.Entity("eAgenda.WebApp.ModuloTarefa.Dominio.ItemTarefa", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("EstaConcluido")
                        .HasColumnType("bit");

                    b.Property<Guid>("TarefaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id")
                        .HasName("PK_TBItemTarefa");

                    b.HasIndex("TarefaId");

                    b.ToTable("TBItemTarefa", (string)null);
                });

            modelBuilder.Entity("eAgenda.WebApp.ModuloTarefa.Dominio.Tarefa", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("DataConclusao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime2");

                    b.Property<int>("Prioridade")
                        .HasColumnType("int");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id")
                        .HasName("PK_TBTarefa");

                    b.ToTable("TBTarefa", (string)null);
                });

            modelBuilder.Entity("CategoriaDespesa", b =>
                {
                    b.HasOne("eAgenda.WebApp.ModuloCategoria.Dominio.Categoria", null)
                        .WithMany()
                        .HasForeignKey("CategoriasId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("eAgenda.WebApp.ModuloDespesa.Dominio.Despesa", null)
                        .WithMany()
                        .HasForeignKey("DespesasId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("eAgenda.WebApp.ModuloCompromisso.Dominio.Compromisso", b =>
                {
                    b.HasOne("eAgenda.WebApp.ModuloContato.Dominio.Contato", "Contato")
                        .WithMany()
                        .HasForeignKey("ContatoId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .HasConstraintName("FK_TBCompromisso_TBContato");

                    b.Navigation("Contato");
                });

            modelBuilder.Entity("eAgenda.WebApp.ModuloTarefa.Dominio.ItemTarefa", b =>
                {
                    b.HasOne("eAgenda.WebApp.ModuloTarefa.Dominio.Tarefa", "Tarefa")
                        .WithMany("Itens")
                        .HasForeignKey("TarefaId")
                        .OnDelete(DeleteBehavior.ClientCascade)
                        .IsRequired()
                        .HasConstraintName("FK_TBItemTarefa_TBTarefa");

                    b.Navigation("Tarefa");
                });

            modelBuilder.Entity("eAgenda.WebApp.ModuloTarefa.Dominio.Tarefa", b =>
                {
                    b.Navigation("Itens");
                });
#pragma warning restore 612, 618
        }
    }
}
